const users = [
    {
        id: 1,
        name: 'Tony Reichert',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        phone: '+1 555 555 5555',
        conversation: [
            {
                sender: 'userConversation',
                message: '¡Hola! Necesito ayuda con la configuración de mi cuenta.',
                timestamp: '2023-11-09T12:00:00Z',
            },
            {
                sender: 'agent',
                message: '¡Hola Tony! ¿Cómo podemos ayudarte hoy?',
                timestamp: '2023-11-09T12:05:00Z',
            },
            {
                sender: 'userConversation',
                message: 'Estoy teniendo problemas para actualizar mi foto de perfil.',
                timestamp: '2023-11-09T12:10:00Z',
            },
            {
                sender: 'agent',
                message: 'Entiendo. Intentaré solucionarlo, un momento por favor.',
                timestamp: '2023-11-09T12:15:00Z',
            },
            {
                sender: 'agent',
                message: 'Tony, he pasado tu caso al equipo técnico. Un agente de la tienda te asistirá en breve.',
                timestamp: '2023-11-09T12:20:00Z',
            },
            {
                sender: 'store',
                message: 'Hola Tony, soy del equipo de soporte técnico. Estoy revisando tu problema con la foto de perfil.',
                timestamp: '2023-11-09T12:25:00Z',
            },
            {
                sender: 'userConversation',
                message: 'Gracias, aprecio la ayuda.',
                timestamp: '2023-11-09T12:30:00Z',
            },
            {
                sender: 'store',
                message: 'Parece que hay un ajuste temporal en nuestro servidor. Por favor, intenta actualizar tu foto de perfil nuevamente.',
                timestamp: '2023-11-09T12:35:00Z',
            },
            {
                sender: 'userConversation',
                message: 'Voy a intentarlo, dame un segundo.',
                timestamp: '2023-11-09T12:40:00Z',
            }
        ],
        channel: 'facebook',
        status: 'active'
    },
    {
        id: 2,
        name: 'Zoey Lang',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'instagram',
        status: 'paused',
    },
    {
        id: 3,
        name: 'Jane Fisher',
        avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'shopify',
        status: 'active',
    },
    {
        id: 4,
        name: 'William Howard',
        avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'woocommerce',
        status: 'clouse',
    },
    {
        id: 5,
        name: 'Kristen Copper',
        avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'whatsapp',
        status: 'active',
    },
    {
        id: 6,
        name: 'Brian Kim',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'facebook',
        status: 'active',
    },
    {
        id: 7,
        name: 'Michael Hunt',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e29027007d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'instagram',
        status: 'paused',
    },
    {
        id: 8,
        name: 'Samantha Brooks',
        avatar: 'https://i.pravatar.cc/150?u=a042581f4e27027008d',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'shopify',
        status: 'active',
    },
    {
        id: 9,
        name: 'Frank Harrison',
        avatar: 'https://i.pravatar.cc/150?img=1',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'woocommerce',
        status: 'clouse',
    },
    {
        id: 10,
        name: 'Emma Adams',
        avatar: 'https://i.pravatar.cc/150?img=2',
        phone: '+1 555 555 5555',
        conversation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc.',
        channel: 'whatsapp',
        status: 'active',
    },
];

export { users };
