import {WhatsappMessage} from "@/lib/whatsapp/models/message/WhatsappMessage";
import {ConversationStatus} from "@/lib/common/models/ConversationStatus";
import {Exception} from "@/lib/common/models/Exception";

export class RepositoryException implements Exception {
  constructor(readonly message: string) {}
}

export interface WhatsappRepository {
  /**
   * Get the plans of a business related to a specific whatsapp channel.
   * @param whatsappId
   * @returns {Promise<{
   *   plandId: string,
   *   startDate: Date,
   *   endDate: Date,
   *   messagesLimit: number | null
   * }[]>}
   */
  getPlansByWhatsappId(whatsappId: string): Promise<{
    planId: string,
    startDate: Date,
    endDate: Date,
    messagesLimit: number | null
  }[]>

  /**
   * Get the source of a message
   * @param whapiMessageId The ID generated by the Whapi service to identify a particular message.
   * @returns {Promise<number>} number indicating the source of the message
   * @throws RepositoryException if the message is not found
   */
  getMessageSource(whapiMessageId: string): Promise<number>

  /**
   * Deactivates a plan for a business
   * @param planId
   */
  deactivateBusinessPlan(planId: string): Promise<void>

  /**
   * Saves a message
   * @param data
   */
  saveMessage(data: WhatsappMessage): Promise<void>

  /**
   * Get the status of a conversation.
   * @param conversationId
   * @returns {Promise<number>} number indicating the status of the conversation
   * @throws RepositoryException if the conversation status is not found
   */
  getConversationStatus(conversationId: string): Promise<number>

  /**
   * Updates the status of a message
   * @param whapiMessageId the ID generated by the Whapi service to identify a particular message.
   * @param status the status of the message
   */
  updateMessageStatus(whapiMessageId: string, status: number): Promise<void>

  /**
   * Updates the status of a whatsapp conversation
   * @param conversationId {string}
   * @param status {ConversationStatus}
   */
  updateConversationStatus(conversationId: string, status: ConversationStatus): Promise<void>

  /**
   * Retrieves the business location associated with a whatsapp channel
   * @param whatsappId {string}
   */
  getBusinessLocationByWhatsappId(whatsappId: string): Promise<string>

  /**
   * Retrieves the whatsapp token associated with a whatsapp channel.
   * The token is used to authenticate the channel with the Whapi service and send messages.
   *
   * @param whatsappId Whatsapp channel ID
   * @returns {Promise<string>} Whatsapp token
   */
  getWhatsappTokenByWhatsappId(whatsappId: string): Promise<string>

  /**
   * Increases the message count usage of a whatsapp channel.
   * @param whatsappId Whatsapp channel ID
   * @param amount Amount to increase the message count usage.
   */
  increaseMessageCountUsage(whatsappId: string, amount: number): Promise<void>

  getConversationId(whatsappId: string, whapiChatId: string): Promise<string>

  getBusinessHours(businessLocationId: string): Promise<object>

  isNumberBlackListed(whatsappId:string, number: string): Promise<boolean>
}
